apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: CLUSTER_NAME_PLACEHOLDER-pullsecret
  namespace: clusters
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: virt-creds-store
    kind: SecretStore
  target:
    name: pullsecret-cluster-CLUSTER_NAME_PLACEHOLDER
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: "{{ .pullSecret | toString }}"
  data:
  - secretKey: pullSecret
    remoteRef:
      key: virt-creds
      property: pullSecret
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: CLUSTER_NAME_PLACEHOLDER-sshkey
  namespace: clusters
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: virt-creds-store
    kind: SecretStore
  target:
    name: sshkey-cluster-CLUSTER_NAME_PLACEHOLDER
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        id_rsa.pub: "{{ .sshPublicKey | toString }}"
  data:
  - secretKey: sshPublicKey
    remoteRef:
      key: virt-creds
      property: ssh-publickey
