apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: external-secrets-base

resources:
  - secretstore.yaml

labels:
  - pairs:
      app.kubernetes.io/name: external-secrets
      app.kubernetes.io/part-of: openshift-lab
      app.kubernetes.io/managed-by: kustomize

# Default namespace
namespace: clusters
