apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: portworx-rwx-block
allowVolumeExpansion: true
parameters:
  repl: "1"
provisioner: pxd.portworx.com
reclaimPolicy: Delete
volumeBindingMode: Immediate
