apiVersion: hypershift.openshift.io/v1beta1
kind: HostedCluster
metadata:
  name: CLUSTER_NAME_PLACEHOLDER
  namespace: CLUSTER_NAMESPACE_PLACEHOLDER
  labels:
    cluster.open-cluster-management.io/clusterset: default
    environment: dev
    cluster-type: hosted-control-plane
  annotations:
    hypershift.openshift.io/cluster-api-provider: KubeVirt
spec:
  release:
    image: quay.io/openshift-release-dev/ocp-release:4.18.20-x86_64
  pullSecret:
    name: pullsecret-cluster-CLUSTER_NAME_PLACEHOLDER
  sshKey:
    name: sshkey-cluster-CLUSTER_NAME_PLACEHOLDER
  networking:
    clusterNetwork:
    - cidr: 10.132.0.0/14
    serviceNetwork:
    - cidr: 172.31.0.0/16
    networkType: OVNKubernetes
  platform:
    type: KubeVirt
    kubevirt:
      baseDomainPassthrough: true
  infraID: CLUSTER_NAME_PLACEHOLDER
  dns:
    baseDomain: apps.tosins-dev-cluster.sandbox1271.opentlc.com
  services:
  - service: APIServer
    servicePublishingStrategy:
      type: LoadBalancer
  - service: OAuthServer
    servicePublishingStrategy:
      type: Route
  - service: OIDC
    servicePublishingStrategy:
      type: Route
  - service: Konnectivity
    servicePublishingStrategy:
      type: Route
  - service: Ignition
    servicePublishingStrategy:
      type: Route
  controllerAvailabilityPolicy: HighlyAvailable
  infrastructureAvailabilityPolicy: HighlyAvailable
