apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: external-secrets-default

resources:
  - ../../base

labels:
  - pairs:
      environment: default
      managed-by: kustomize
