apiVersion: v1
kind: Namespace
metadata:
  name: external-secrets-operator
  labels:
    name: external-secrets-operator
    app.kubernetes.io/name: external-secrets-operator
    app.kubernetes.io/part-of: openshift-hypershift-lab
    app.kubernetes.io/managed-by: kustomize
