---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metal3-provisioning
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  destination:
    namespace: openshift-cnv
    server: https://kubernetes.default.svc
  project: default
  source:
    path: gitops/cluster-config/metal3-provisioning/overlays/aws-dev
    repoURL: https://github.com/tosin2013/openshift-hypershift-lab.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true

