---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: multicluster-engine
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  destination:
    namespace: open-cluster-management
    server: https://kubernetes.default.svc
  project: default
  source:
    path: gitops/cluster-config/rhacm-instance/overlays/basic
    repoURL: https://github.com/tosin2013/openshift-hypershift-lab.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true

