apiVersion: v1
data:
  versions.yaml: |
    version: 3.5.0
    components:
      stork: registry.portworx.io/portworx/dsahoo/stork:eep
      autopilot: registry.portworx.io/portworx/autopilot:1.3.18
      clusterDiags: registry.portworx.io/portworx/cluster-diags:3.4.2
      csiNodeDriverRegistrar: registry.portworx.io/portworx/csi-node-driver-registrar:v2.15.0
      csiProvisioner: registry.portworx.io/portworx/csi-provisioner:v5.3.0
      csiResizer: registry.portworx.io/portworx/csi-resizer:v1.14.0
      csiSnapshotter: registry.portworx.io/portworx/csi-snapshotter:v8.3.0
      csiSnapshotController: registry.portworx.io/portworx/snapshot-controller:v8.3.0
      telemetry: registry.portworx.io/portworx/ccm-go:1.4.30
      pxLibUpdate: registry.portworx.io/portworx/px-lib:pxfslibs-3.5.0.0-mver12-update
      metricsCollector: registry.portworx.io/portworx/realtime-metrics:1.0.32
      telemetryProxy: registry.portworx.io/portworx/telemetry-envoy:1.1.18
      logUploader: registry.portworx.io/portworx/log-upload:px-1.1.46
      dynamicPlugin: registry.portworx.io/portworx/portworx-dynamic-plugin:2.1.0
      dynamicPluginProxy: registry.portworx.io/portworx/nginx-unprivileged:alpine-slim
      kubeScheduler: registry.portworx.io/portworx/kube-scheduler-amd64:v1.33.5
      kubeControllerManager: registry.portworx.io/portworx/kube-controller-manager-amd64:v1.33.5
      pause: registry.portworx.io/portworx/pause:3.1
kind: ConfigMap
metadata:
  name: px-versions
  namespace: portworx
